version: '3'

services:
    # busybox
    fuseki-data-1:
        image: busybox
        container_name: fuseki_data-1
        volumes: # -v option
            - /fuseki # this name should be unique in the network
    fuseki-data-2:
        image: busybox
        container_name: fuseki_data-2
        volumes: 
            - /fuseki
    fuseki-data-3:
        image: busybox
        container_name: fuseki_data-3
        volumes: 
            - /fuseki
    fuseki-data-4:
        image: busybox
        container_name: fuseki_data-4
        volumes: 
            - /fuseki
    fuseki-data-5:
        image: busybox
        container_name: fuseki_data-5
        volumes: 
            - /fuseki 
    
    # Fuseki
    fuseki-1:
        image: stain/jena-fuseki
        container_name: fuseki-1 # prevent auto-naming
        platform: linux/amd64
        depends_on: 
            - fuseki-data-1
        ports: # -p option
            - "3031:3030"
        environment: # -e option
            - ADMIN_PASSWORD=umbc_ebiquity
        cap_add:
            - NET_ADMIN
    fuseki-2:
        image: stain/jena-fuseki
        container_name: fuseki-2
        platform: linux/amd64
        depends_on: 
            - fuseki-data-2
        ports: 
            - "3032:3030"
        environment: 
            - ADMIN_PASSWORD=umbc_ebiquity
        cap_add:
            - NET_ADMIN
    fuseki-3:
        image: stain/jena-fuseki
        container_name: fuseki-3
        platform: linux/amd64
        depends_on: 
            - fuseki-data-3
        ports: 
            - "3033:3030"
        environment: 
            - ADMIN_PASSWORD=umbc_ebiquity
        cap_add:
            - NET_ADMIN
    fuseki-4:
        image: stain/jena-fuseki
        container_name: fuseki-4
        platform: linux/amd64
        depends_on: 
            - fuseki-data-4
        ports: 
            - "3034:3030"
        environment: 
            - ADMIN_PASSWORD=umbc_ebiquity
        cap_add:
            - NET_ADMIN
    fuseki-5:
        image: stain/jena-fuseki
        container_name: fuseki-5
        platform: linux/amd64
        depends_on: 
            - fuseki-data-5
        ports: 
            - "3035:3030"
        environment: 
            - ADMIN_PASSWORD=umbc_ebiquity
        cap_add:
            - NET_ADMIN
    