"""Update User table: type and user_id

Revision ID: e0190120b535
Revises: 4ce1f096eabb
Create Date: 2023-01-19 15:17:32.446462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0190120b535'
down_revision = '4ce1f096eabb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('type', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('user_id', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_column('user', 'user_id')
    op.drop_column('user', 'type')
    # ### end Alembic commands ###
